#
# This file contains configuration flags to customize your site
#

author:
  name: 'Artyom Tetyukhin'

title: 'Artyom Tetyukhin'
description: 'My personal blog about the little stuff I know'

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: arttet

# My social media sites.
github:
  name: arttet
  icon: svg/github.svg

linkedin:
  name: arttet
  icon: svg/linkedin.svg

leetcode:
  name: arttet
  icon: svg/leetcode.svg

hackerrank:
  name: arttet
  icon: svg/hackerrank.svg

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-141924660-1

sidebar_home_link: True
paginate:          5
# paginate_path:    '/page:num'

# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-toc
