export const codeThemes = [
  {
    id: 'catppuccin-mocha',
    label: 'Catppuccin Mocha',
    kind: 'dark',
    accent: '#cba6f7',
    bg: '#1e1e2e',
    fg: '#cdd6f4',
  },
  {
    id: 'github-dark',
    label: 'GitHub Dark',
    kind: 'dark',
    accent: '#58a6ff',
    bg: '#0d1117',
    fg: '#c9d1d9',
  },
  {
    id: 'gruvbox-dark-hard',
    label: 'Gruvbox Dark',
    kind: 'dark',
    accent: '#fabd2f',
    bg: '#1d2021',
    fg: '#ebdbb2',
  },
  {
    id: 'github-light',
    label: 'GitHub Light',
    kind: 'light',
    accent: '#0550ae',
    bg: '#ffffff',
    fg: '#24292e',
  },
  {
    id: 'catppuccin-latte',
    label: 'Catppuccin Latte',
    kind: 'light',
    accent: '#8839ef',
    bg: '#eff1f5',
    fg: '#4c4f69',
  },
  {
    id: 'gruvbox-light-hard',
    label: 'Gruvbox Light',
    kind: 'light',
    accent: '#af3a03',
    bg: '#f9f5d7',
    fg: '#3c3836',
  },
];
